name: render

on: workflow_dispatch

env:
  EMSCRIPTEN_VERSION: 2.0.26
  URL_BLENDER: https://ftp.nluug.nl/pub/graphics/blender/release/Blender2.93/blender-2.93.2-linux-x64.tar.xz
  URL_PIX3D: http://pix3d.csail.mit.edu/data/pix3d.zip

jobs:

  render:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Blender
        run: wget -q ${{env.URL_BLENDER}} && mkdir ~/blender && tar -xf $(basename ${{env.URL_BLENDER}}) --strip-components=1 -C ~/blender
      
      - name: Pix3D
        run: wget -q ${{env.URL_PIX3D}} && unzip pix3d.zip -d ~/pix3d
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Render
        run: ~/blender/blender -noaudio --background --python render_pix3d.py -- --input-path ~/pix3d --output-path ~ --render-synthetic-views

      - name: Archive renders
        run: tar -cf ~/pix3d_renders.tar pix3d_renders -C ~

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hub release create -m "Pix3D renders" -a ~/pix3d_renders.tar build_${{github.sha}}
